# wrangler.toml
name = 'edge-tunnel'

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"

[observability]
[observability.logs]
enabled = false
invocation_logs = true

[vars]
UUID = "123e4567-e89b-12d3-a456-426614174000"
