# wrangler.toml
name = 'edge-tunnel'

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"

[vars]
# UUID = "example_dev_token"

[observability]
[observability.logs]
enabled = false
invocation_logs = true
